INSERT INTO user (`user_id`, `email`, `password`)
VALUES ('Marlee', 'marMom@gmail.com', 'aabb111222');
INSERT INTO user (`user_id`, `email`, `password`)
VALUES ('Harlee', 'marMom@gmail.com', 'aabb111222');
INSERT INTO user (`user_id`, `email`, `password`)
VALUES ('Farley', 'marMom@gmail.com', 'aabb111222');
INSERT INTO user (`user_id`, `email`, `password`)
VALUES ('Parley', 'marMom@gmail.com', 'aabb111222');
INSERT INTO user (`user_id`, `email`, `password`)
VALUES ('Charlie', 'marMom@gmail.com', 'aabb111222');
INSERT INTO user (`user_id`, `email`, `password`)
VALUES ('Carlie', 'marMom@gmail.com', 'aabb111222');
INSERT INTO user (`user_id`, `email`, `password`)
VALUES ('Calvin', 'MrsHobbes@gmail.com', 'aabb111222');

INSERT INTO flashcard (flashcard_deck_id, front_text, back_text, front_image, back_image, right_answer, wrong_answer) 
VALUES (1, 'What animal is this?', 'This is a Lynx. Lynx have a short tail and characteristic tufts of black hair on the tips of their ears; large, padded paws for walking on snow; and long whiskers on the face. Under their neck, they have a ruff which has black bars, is not very visible, and resembles a bow tie.', 'http://upload.wikimedia.org/wikipedia/commons/6/68/Lynx_lynx_poing.jpg', 'http://upload.wikimedia.org/wikipedia/commons/6/68/Lynx_lynx_poing.jpg', 'This is a lynx!', 'This is a lion!');
INSERT INTO flashcard (flashcard_deck_id, front_text, back_text, front_image, back_image, right_answer, wrong_answer) 
VALUES (1, 'What animal is this?', 'This is a Platypus! The Playtypus is the only mammal (apart from at least one species of dolphin) known to have a sense of electroreception: they locate their prey in part by detecting electric fields generated by muscular contractions. The platypus electroreception is the most sensitive of all mammals.', 'http://photovide.com/wp-content/uploads/2012/03/Platypus-Babies-005.jpg','http://photovide.com/wp-content/uploads/2012/03/Platypus-Babies-005.jpg', 'This is a platypus!', 'This is a duck!');
INSERT INTO flashcard (flashcard_deck_id, front_text, back_text, front_image, back_image, right_answer, wrong_answer) 
VALUES (1, 'What animal is this?', 'This is a Hyena! Hyenas are a genetic half-step between a dog and a cat, and have qualities of BOTH!', 'http://fc09.deviantart.net/fs71/i/2012/154/5/6/cute_hyena_by_theogoth-d524d51.jpg', 'http://fc09.deviantart.net/fs71/i/2012/154/5/6/cute_hyena_by_theogoth-d524d51.jpg', 'This is a Hyena!', 'This is a Dingo!');